export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNOUT = 'USER_SIGNOUT';

export const GOOGLE_SIGNIN_REQUEST = 'GOOGLE_SIGNIN_REQUEST';
export const GOOGLE_SIGNIN_FAIL = 'GOOGLE_SIGNIN_FAIL';
export const GOOGLE_SIGNIN_SUCCESS = 'GOOGLE_SIGNIN_SUCCESS';
export const GOOGLE_SIGNOUT = 'GOOGLE_SIGNOUT';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST';
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL';
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS';

export const USER_GET_REQUEST = 'USER_GET_REQUEST';
export const USER_GET_FAIL = 'USER_GET_FAIL';
export const USER_GET_SUCCESS = 'USER_GET_SUCCESS';

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_RESET = 'USER_UPDATE_RESET';
export const IS_MOBILE = 'IS_MOBILE';
