export default {
  products: [
    {
      _id: "1",
      name: "Shirt Nike",
      category: "Shirts",
      image: "/images/d1.jpg",
      price: 50,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
    },
    {
      _id: "2",
      name: "Sweet Nike",
      category: "Shirts",
      image: "/images/d2.jpg",
      price: 45,
      brand: "Nike",
      rating: 5,
      numReviews: 20,
    },
    {
      _id: "3",
      name: "Sweet Nike",
      category: "Shirts",
      image: "/images/d3.jpg",
      price: 55,
      brand: "Nike",
      rating: 3,
      numReviews: 15,
    },
    {
      _id: "4",
      name: "Air Max",
      category: "Shoes",
      image: "/images/d4.jpg",
      price: 180,
      brand: "Nike",
      rating: 5,
      numReviews: 35,
    },
    {
      _id: "5",
      name: "Jogging slim",
      category: "Pants",
      image: "/images/d5.jpg",
      price: 60,
      brand: "Nike",
      rating: 1,
      numReviews: 10,
    },
    {
      _id: "6",
      name: "Jogging",
      category: "Pants",
      image: "/images/d6.jpg",
      price: 40,
      brand: "Nike",
      rating: 3.5,
      numReviews: 30,
    },
  ],
};
